# Toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# Markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']
hook_add = '''
    let g:vim_markdown_folding_disabled = 1
    let g:vim_markdown_new_list_item_indent = 0
'''

## Preview markdown document with html 
#[[plugins]]
#repo = 'previm/previm'
#on_ft = ['md']
#hook_add = '''
#    nnoremap <silent> <C-p> :PrevimOpen<CR>
#'''

[[plugins]]
repo = 'aklt/plantuml-syntax'
on_ft = ['uml']

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_ft = ['c', 'cpp']
on_event = 'InsertEnter'
depends = ['deoplete.nvim']

# clang-format
[[plugins]]
repo = 'rhysd/vim-clang-format'
on_ft = ['c', 'cpp']
on_map = ['<Plug>(operator-clang-format)']
depends = ['kana/vim-operator-user']
# Do indent by clang-format
# Google style with indent width 4
hook_add = '''
    vmap f= <Plug>(operator-clang-format)
    let g:clang_format#style_options = {
        \ "BasedOnStyle" : 'Google',
        \ "TabWidth" : 4,
        \ "IndentWidth" : 4,
        \ "UseTab" : 'Never',
        \ "AccessModifierOffset" : -4,
        \ "Standard" : "C++11",
    \ }
    set cino=g0.5s,h0.5s
'''

# Python
[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = ['python']

#[[plugins]]
#repo = 'jelera/vim-javascript-syntax'

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']
hook_add = '''
    let g:javascript_plugin_jsdoc = 1
'''

# Javascript ES6 syntax
[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript']

[[plugins]]
repo = 'isRuslan/vim-es6'
on_ft = ['javascript']

# Add javascript comment with JsDoc
[[plugins]]
repo = 'heavenshell/vim-jsdoc'
on_ft = ['javascript']
hook_add = '''
    noremap <C-j> :JsDoc<CR>
'''

# gitignore sytax
[[plugins]]
repo = 'gisphm/vim-gitignore'
on_ft = ['gitignore']

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = '''
    let g:deoplete#enable_at_startup = 1
    set completeopt-=preview
'''
on_event = 'InsertEnter'

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
    imap <C-]> <Plug>(neosnippet_expand_or_jump)
    smap <C-]> <Plug>(neosnippet_expand_or_jump)
    xmap <C-]> <Plug>(neosnippet_expand_target)
    let g:neosnippet#snippets_directory='${NVIM_HOME}/snippets/'
'''
on_event = 'InsertEnter'
on_ft = ['snippet']
depends = ['neosnippet-snippets']

# Rust
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']

# Yaml
repo = 'chase/vim-ansible-yaml'
hook_source = '''
    let g:ansible_options = {'ignore_blank_lines': 0}
'''
on_ft = ['ansible']
